name: CD Test

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.AWS_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Create .env File
      run: |
        echo "${{ secrets.DEV_ENV_FILE }}" > .env

    - name: Deploy Nebula AI Stack to AWS
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" docker-compose.dev.yml .env ubuntu@${{ secrets.DEV_FASTAPI_IP }}:/home/ubuntu/

        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.DEV_FASTAPI_IP }} << EOF
          sudo mkdir -p /mnt/extra/chroma_db
          sudo chmod 777 /mnt/extra/chroma_db

          docker compose -f /home/ubuntu/docker-compose.dev.yml up -d --build
        EOF
