name: CD Test

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Create .env File
      run: |
        echo "${{ secrets.DEV_ENV_FILE }}" > .env

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.AWS_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy FastAPI to AWS
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.DEV_FASTAPI_IP }} << EOF
          cd /home/ubuntu/
          git pull origin dev
          docker-compose -f docker-compose.fastapi.dev.yml up -d --build
        EOF

    - name: Deploy Celery to AWS
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.DEV_CELERY_IP }} << EOF
          cd /home/ubuntu/
          git pull origin dev
          docker-compose -f docker-compose.celery.dev.yml up -d --build
        EOF

    - name: Deploy ChromaDB to AWS
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.DEV_CHROMA_IP }} << EOF
          cd /home/ubuntu/
          git pull origin dev
          docker-compose -f docker-compose.chroma.dev.yml up -d --build
        EOF
