name: Dev Branch LocalStack EC2 deploy
on:
  push:
    branches:
      - dev

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout dev
        uses: actions/checkout@v4
  
      - name: Connect to EC2 and pull Docker image
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USERNAME }}
          EC2_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > ec2_key.pem
          chmod 400 ec2_key.pem
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST '
            # sudo 설치
            if ! command -v sudo &> /dev/null; then
              apt update && apt install -y sudo
            fi
            
            # Docker 설치
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
  
            # Docker 서비스 시작 및 활성화
            sudo systemctl start docker
            sudo systemctl enable docker
    
            # Docker 버전 확인
            docker --version

            # 명령어 실행
            sudo docker rm -f $(sudo docker ps -qa)
            sudo docker pull wonjun0120/nebula-ai
            sudo docker-compose up -d
            sudo docker image prune -f
          '
          
