name: Dev Branch EC2 deploy
on:
  push:
    branches:
      - dev

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout dev
        uses: actions/checkout@v4
  
      - name: Connect to EC2 and pull Docker image
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USERNAME }}
          EC2_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > ec2_key.pem
          chmod 400 ec2_key.pem
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST '
            docker pull your-docker-image:latest
            docker run -d your-docker-image:latest
          '
