name: Dev Branch EC2 deploy
on:
  push:
    branches:
      - dev

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout dev
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Verify zrok installation
        run: |
          PATH=~/bin:$PATH
          zrok version 
          
      - name: Connect to LocalStack EC2 via zrok
        env:
          ZROK_URL: ${{ secrets.ZROK_URL }}
        run: |
          zrok access private $ZROK_URL &
          sleep 5  # Wait for the connection to establish

      - name: Deploy to test, localstack
        uses: appleboy/ssh-action@v0.1.6
        id: deploy-localstack
        if: contains(github.ref, 'dev')
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          envs: GITHUB_SHA
          script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull wonjun0120/nebula-ai
            docker-compose up -d
            docker image prune -f
